### ISSUE TITLE
Failing to compile with hw and xen 

### ISSUE THREAD

**Issue by ihearta380** [rumpkernel/rumprun#102]
for the past 3 days I have been trying to get this to compile as to the instructions with this error. Now i need some help. Thank You

 `o -o /home/timothy/rumprun/./obj-amd64-hw/rumprun.o \
    -L/home/timothy/rumprun/./obj-amd64-hw/lib/libbmk_core -L/home/timothy/rumprun/./obj-amd64-hw/lib/libbmk_rumpuser \
    -Wl,--whole-archive -lbmk_rumpuser -lbmk_core -Wl,--no-whole-archive
/usr/bin/ld: -r and -pie may not be used together
collect2: error: ld returned 1 exit status
Makefile:57: recipe for target '/home/timothy/rumprun/./obj-amd64-hw/rumprun.o' failed
make: *** [/home/timothy/rumprun/./obj-amd64-hw/rumprun.o] Error 1
`

`gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.3.0-12ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)`

**Comment by gandro** [comment]
This seems to be related to #99

**Comment by liuw** [comment]
Also #100 

There was code there. Someone just needs to properly add in the missing bits.
