### ISSUE TITLE
about unexpected halt

### ISSUE THREAD

**Issue by sjtugjy** [rumpkernel/rumprun#105]
I meet a problem that the rumprun may halt for unknown reasons.
I build rumprun as a xen guest (just runs helloworld). However, sometimes it may halt or loop deadly without any progress (no more output and no crash). 
In most cases, the last output is as follows:
"Failed to read device/pci/0/backend-id.
no backend"
For normal execution, there should be other outputs follows the above one.

Has anyone met a similar problem?

**Comment by liuw** [comment]
Have you tried to run a normal guest on your Xen host first?

I don't think the PCI message is fatal.

Without complete log or steps to reproduce I don't have immediate idea what could go wrong.
