### ISSUE TITLE
polling for POLLOUT on standard output fails

### ISSUE THREAD

**Issue by mato** [rumpkernel/rumprun#20]
Consider the following test code, abbreviated:

````
struct pollfd pfd[1];
int rv;
for (;;) {
    pfd[0].fd = 1;
    pfd[0].events = POLLOUT;
    pfd[0].revents = 0;
    printf ("calling poll()\n");
    rv = poll(pfd, 1, 1000);
    printf ("poll() returned: %d, errno = %d, revents = %d\n", rv, errno, pfd[0].revents);
    sleep(1);
}
````

The expected output is:
````
calling poll()
poll() returned: 1, errno = 0, revents = 4
````

Instead, on rumprun-xen I get:
````
calling poll()
poll() returned: 0, errno = 0, revents = 0
PANIC: assert "(thread->bt_flags & THREAD_TIMEDOUT) == 0" FAILED
````

**Comment by mato** [comment]
To clarify the motivation for this: Mirage is trying to do non-blocking writes to the console and these aren't working. My theory is that this is due to Lwt polling fd 1 for POLLOUT but never getting the event.

**Comment by anttikantee** [comment]
There is no console tty driver, so poll() on stdout is expected to fail (but not sure if it's expected to panic the scheduler).

**Comment by mato** [comment]
I don't see any panics with Mirage, only with the above test program.

**Comment by anttikantee** [comment]
On 26/05/15 14:37, Martin Lucina wrote:
> I don't see any panics with Mirage, only with the above test program.

Can you expand on what you mean by this comment?

**Comment by mato** [comment]
On Tuesday, 26.05.2015 at 07:41, Antti Kantee wrote:
> On 26/05/15 14:37, Martin Lucina wrote:
> > I don't see any panics with Mirage, only with the above test program.
> 
> Can you expand on what you mean by this comment?

Err, well, just that it looks like it's the poll() followed by sleep()
which is triggering the PANIC.

Regarding poll() itself, it should be enough to fix this if I implement an
.fo_poll() for rumpcons, right?

**Comment by anttikantee** [comment]
On 26/05/15 14:44, Martin Lucina wrote:
> On Tuesday, 26.05.2015 at 07:41, Antti Kantee wrote:
>> On 26/05/15 14:37, Martin Lucina wrote:
>>> I don't see any panics with Mirage, only with the above test program.
>>
>> Can you expand on what you mean by this comment?
>
> Err, well, just that it looks like it's the poll() followed by sleep()
> which is triggering the PANIC.

Yea there's a bug in the scheduler.  It's easy to "fix", but I'd rather 
do a more complete revamp to actually fix the problem.  If you're not a 
terrible hurry, I'd like to finish with the thing I'm currently fixing 
first.

> Regarding poll() itself, it should be enough to fix this if I implement an
> .fo_poll() for rumpcons, right?

Only one way to find out.

**Comment by mato** [comment]
> Only one way to find out.
Done, tested, seems to work. Patch sent to the mailing list.

**Comment by anttikantee** [comment]
Both subproblems should be fixed now.
