### ISSUE TITLE
xen/bmk: implement out-of-band timecounter for more accurate timekeeping

### ISSUE THREAD

**Issue by mato** [rumpkernel/rumprun#3]
Due to the combination of -xen and -bmk using a cooperative scheduler and the rump kernel clock driver depending on soft interrupts being scheduled, if an application calls `gettimeofday()` in a loop without calling `sched_yield()` then the time values returned are not updated.

This is commonly used in applications to (for example) determine the frequency of a hardware time stamp counter:
````c
    cycles_t cycles_start = get_cycles(),
             cycles_end;
    usecs_t usecs_start = get_usecs(),
            usecs_end;
    for (i= 0; i < 1000000; ++i)
    {
        usecs_end = get_usecs();
        // sched_yield() would need to be called here.
        if (usecs_end - usecs_start > 200)
            break;
    }
    cycles_end = get_cycles();
    cycles_t freq = (1000000ULL * (cycles_end - cycles_start)) /
                    (usecs_end - usecs_start);
````
The above code will crash with a division by zero due to `usecs_end` never being updated.
The solution is to implement an out-of-band timecounter driver for the rump kernel which does not rely on clock interrupts.

**Comment by mato** [comment]
Initial implementation of such a timecounter for -xen is at 92cc89a6.

**Comment by mato** [comment]
Fixed

**Comment by mato** [comment]
Err, fixed for Xen, leaving open to track that this should eventually be done for baremetal.

**Comment by anttikantee** [comment]
The tc driver was made to apply to the hw platform in d5a768eb35653a6104d0577c1f67a234d179e45b
