### ISSUE TITLE
hw: Implement timekeeping

### ISSUE THREAD

**Issue by mato** [rumpkernel/rumprun#30]
As reported  by @talex5 while testing mirage-console on rumprun:

> I also tested mirage-skeleton/console, which worked but ran rather fast (it's supposed to wait 1s between each print). Calling gettimeofday showed the clock running fast for some reason.

@anttikantee notes:

> That's because when I wrote the platform, I didn't bother writing a clock driver, and just used "rtdsc" as an approximation.

**Comment by anttikantee** [comment]
Well, hw clock can run slow too, depending on the speed of the CPU ;-)

The code is in platform/hw/arch/{i386,amd64}/machdep.c::bmk_cpu_clock_now()
(if someone looks at this at a later date, both have probably migrated to arch/x86)

**Comment by mato** [comment]
Fixes for this have now been changed to master. Please test, and file issues for any problems encountered. See also full discussion at http://www.freelists.org/post/rumpkernel-users/Implement-timekeeping-for-rumprunhw-x86.
