### ISSUE TITLE
GCC5.1 build failure

### ISSUE THREAD

**Issue by Incognito** [rumpkernel/rumprun#33]
I ran into some issues https://gist.githubusercontent.com/anonymous/566a26a930fa2d902894/raw/6824c3c138580bff415caddec3bdf1062d560a31/build.log

`CXX=false ./build-rr.sh xen` does work as a workaround.

**Comment by anttikantee** [comment]
I submitted a bug report about this to NetBSD, and there is a proposed patch.  Can you apply it to src-netbsd and see if the build works for you now?

https://gnats.netbsd.org/49989

**Comment by Incognito** [comment]
The build still fails after that patch. https://gist.github.com/Incognito/02ff3d8ce07d013dc628

I tried it with clang++, which fails on some other part, and then finally using g++ will complete the process and I get the success message.

**Comment by Incognito** [comment]
Upstream issue opened as https://gnats.netbsd.org/49990

**Comment by anttikantee** [comment]
Let's keep this issue open until it's fixed in the rumprun tree.

**Comment by anttikantee** [comment]
Should be fixed now.

Thanks for the report!

**Comment by anttikantee** [comment]
The fix was inadequate so I backed it out of NetBSD. The inadequacy doesn't affect rumprun adversely, so for now rumprun remains ok, but will break when pthread_types.h is next updated in src-netbsd.

I'll try to come up with an alternative fix meawhile, but since that's still promiseware, I'm reopening this issue.

**Comment by anttikantee** [comment]
This should be fixed upstream now, so I'm closing this issue.  Notably, the only effect on Rumprun is that things will not break when we next update upstream sources.
