### ISSUE TITLE
allow user-specified rumpbake.conf files

### ISSUE THREAD

**Issue by liuw** [rumpkernel/rumprun#42]
Currently all targets of rumpbake are hardcoded. That means I can't control
what rump components are linked in to the final binary. That's not very
desirable for power users. Being the first one to have such needs I can
certainly foresee other users in the future want to do the same.

I would like to make rumpbake more flexible. That could be done by either
getting rid of the positional arguments or making it accept user provided
config file.

The syntax of rumpbake being experimental means we can get away with any
breakage at this stage.

Thoughts?

**Comment by anttikantee** [comment]
My thought is that you have a valid point, but that this discussion should be on the mailing list.

**Comment by mato** [comment]
Best discussed on the list, but is there anything functionally missing for you right now that you can't do by editing app-tools/rumpbake.conf?

**Comment by liuw** [comment]
OK. Mailing list it is.

**Comment by liuw** [comment]
Editing rumpbake.conf is what I do at the moment. I can certainly live with
that for now.

Anyway, let's discuss that on mailing list instead.

**Comment by anttikantee** [comment]
Here's the thread:
https://www.freelists.org/post/rumpkernel-users/Make-rumpbake-more-flexible

I'm changing the subject of this issue to "allow user-specified rumpbake.conf files"

**Comment by anttikantee** [comment]
This functionality is implemented by rumpbake -c userconf.
