### ISSUE TITLE
Specify default C++ standard in a non-broken way

### ISSUE THREAD

**Issue by anttikantee** [rumpkernel/rumprun#43]
Currently, we require at least c++11.  Since not all compilers default to at least c++11, we need a default standard.  That default is currently set in the compiler wrapper (the one generated from `cc.in`) when the C++ compiler is used.  That least to the following window of brokenness:

```
gcc -c foo.cc
g++ -o foo foo.o
```

I have not found a way to specify `-std=c++11` so that it is used for cpp only when c++ is being compiled.  If we don't specify it for cpp, the value of `_cplusplus` is wrong.  If we do, gcc will complain if you do not build c++ code.

**Comment by mato** [comment]
I don't follow why this is an issue. `gcc` is a *C* compiler, unless you know of software that expects to compile C++ code with a C compiler and have things work, it's a red herring.

**Comment by anttikantee** [comment]
It's an issue because doing so works and I wouldn't be surprised if existing software does it.

**Comment by mato** [comment]
Where does the C++11 requirement come from? The new libc++ upstream? Another issue is, how will specifying the C++ standard in our compiler wrapper interact with application build systems that manually specify a different standard?

**Comment by anttikantee** [comment]
Yes, from there.

The manually specified one will "win".  If it's <c++11, too bad (can't really fix that).

**Comment by mato** [comment]
I've pushed a possible fix to the wip-stdcpp branch. Will see what travis says, if it doesn't break anything we should be able to use this approach for the rest of the C++-specific bits (e.g. -lrumprun_unwind).

**Comment by mato** [comment]
Seems to work, pushed to master with a clarified commit message. FWIW, I use the following test program to verify that the right thing happens all the way through the toolchain:
````
#include <iostream>

int main()
{
    std::cout << __cplusplus << std::endl;
    return 0;
}
````
This can now be built both with `gcc -c`, followed by linking with `g++`, so this should be fixed.

**Comment by mato** [comment]
Further updated in 1fd095a to *default* to C++-11, ie. not override a manually-specified -std=.

**Comment by anttikantee** [comment]
thanks!
