### ISSUE TITLE
gcc may generate references not satisfied by libc++ (HIGH PRIORITY)

### ISSUE THREAD

**Issue by anttikantee** [rumpkernel/rumprun#44]
how-to-repeat:

* build rumprun against NetBSD HEAD
* build pcre from rumprun-packages against said build

Result:

```
  CXXLD    pcrecpp_unittest
pcrecpp_unittest: In function `pcrecpp::RE::DoMatch(pcrecpp::StringPiece const&, pcrecpp::RE::Anchor, int*, pcrecpp::Arg const* const*, int) const':
(.text+0x57ce): undefined reference to `__cxa_throw_bad_array_new_length'
collect2: error: ld returned 1 exit status
```

This is a high priority problem since it prevents from updating to latest NetBSD sources.

**Comment by mato** [comment]
Which GCC version are you building with? Based on some googling, this looks like an ABI mismatch between GCC and the C++ runtime bits.

**Comment by anttikantee** [comment]
4.9.2

**Comment by mato** [comment]
Our toolchain uses `libcxxrt` to implement the low-level C++ ABI. It appears that support for `__cxa_throw_bad_array_new_length` went in around pathscale/libcxxrt@30d2ae539a303f7c3c5e81c58c6a8a477c2b76d9 (but see also later commits which have further fixes). So, the `libcxxrt` in NetBSD upstream, or our copy of it, needs to be updated to a newer version.

**Comment by anttikantee** [comment]
Noting it here too: using the lastest libcxxrt (not in NetBSD) fixes this issue.  Just need to pull it in somehow.

**Comment by mato** [comment]
I'd ask the NetBSD maintainer if he/she can update libcxxrt. If yes, problem solved. If not, I can look into making things work with upstream libcxxrt (and, in this case, probably also libc++) directly.

**Comment by anttikantee** [comment]
Do you think there is anything NetBSD-specific in libcxxrt?  If not, we should cut the "middle-man".  libc++ is probably a different case, since it does provide the NetBSD C++ environment.

**Comment by anttikantee** [comment]
Furthermore, NetBSD has to support 2 compilers, we have to support an indefinite number of compilers.  I think that's also an argument to improve our flexibility wrt to libcxxrt.

(well, this is all speculation which assumes that I correctly understand the function of libcxxrt ;-)
