### ISSUE TITLE
Error when compiling an existing project with rumprun

### ISSUE THREAD

**Issue by h1994st** [rumpkernel/rumprun#47]
Hi,

I followed this [tutorial](https://github.com/rumpkernel/wiki/wiki/Tutorial%3A-Building-Rumprun-Unikernels). And I wanted to compile an existing project with `cmake`.

```
$ cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=../../rumprun/app-tools/x86_64-rumprun-netbsd-toolchain.cmake .
$ make
```

`cmake` was successful. After typing `make`, I got an error:

```
fatal error: sys/cpuset.h: No such file or directory
 #include <sys/cpuset.h>
```

It seems that there is no header file named `cpuset.h` in `rumprun/platform/hw/rump/include/sys`

Does anyone know how to solve this problem?

Thanks!

**Comment by mato** [comment]
Hi,
Rumprun provides a NetBSD "userland" and NetBSD does not have the (Linux) concept of cpusets. I'm assuming your project normally builds on Linux, although I don't see a `sys/cpuset.h` on my Linux system -- is this provided by an external library? In any case, you'll need to modify your project to accomodate that, perhaps by adding the relevant tests to `CMakeLists.txt`.
If you need help, please ask on IRC or on the mailing list.

**Comment by mato** [comment]
(Closing this as it's not a Rumprun issue, cpusets are a Linux-specific feature)

**Comment by h1994st** [comment]
Thanks a lot! I send email to the mailing list!
