### ISSUE TITLE
Delay when using QEMU/KVM port forwarding + DHCP

### ISSUE THREAD

**Issue by davedoesdev** [rumpkernel/rumprun#56]
Per [running the Node.js Express example](https://github.com/rumpkernel/rumprun-packages/tree/master/nodejs#examples), i.e.

```shell
rumprun kvm -M 160 -I 'nic,vioif,-net user,hostfwd=tcp::3000-:3000' -W nic,inet,dhcp -i -b express-$(EXPRESS_VERSION).iso,/express ../build/out/Release/node.bin /express/examples/hello-world/index.js
```

I observed that I had to wait 5 seconds from VM start to get a response from `http://localhost:3000`. I can connect before that but my browser waits until 5 seconds has elapsed from VM start.

I can fix this in two ways:

1. Run with a static address:

   ```shell
   rumprun kvm -M 160 -I 'nic,vioif,-net user,hostfwd=tcp::3000-:3000' -W nic,inet,static,10.0.2.15/24 -i -b express-$(EXPRESS_VERSION).iso,/express ../build/out/Release/node.bin /express/examples/hello-world/index.js
   ```

2. Disable duplicate address detection by always doing `return 0` from `if_do_dad` (`src-netbsd/sys/net/if.c`)

Suspicion is that DHCP causes DAD but static does not, and that while doing DAD, the network interface is in some tentative state that is unable to reply to packets.

**Comment by davedoesdev** [comment]
Issue is brought over from https://github.com/rumpkernel/rumprun-packages/pull/20

**Comment by davedoesdev** [comment]
pcap files (generated using `-g '-net dump'`):

https://gist.github.com/davedoesdev/a6a7fe6349fb150d836b

**Comment by davedoesdev** [comment]
Duplicate address detection is probably OK when not running in VM so if it's disabled maybe it should only be when in VM?

**Comment by anttikantee** [comment]
I'm leaving this open until it's properly fixed, but you should see the effect already now.

**Comment by anttikantee** [comment]
Properly fixed now.
