### ISSUE TITLE
build-rr.sh fails if CDPATH is set

### ISSUE THREAD

**Issue by jsgf** [rumpkernel/rumprun#60]
If CDPATH is set then bash's cd can print the path. This causes platform/hw/pci/Makefile.pci's:
```
PCIDIR!=        cd ${.PARSEDIR} ; pwd -P
```
to set PCIDIR to the same path twice (once from cd, once from pwd).

The fix is to unset CDPATH. I'm guessing either buildrump or build-rr should do this.

**Comment by anttikantee** [comment]
Probably better to get rid of the construct entirely, I don't think it's strictly necessary to do it that way.  Otherwise we might next have to start plugging all the creative ways that people have invented to invoke rc scripts for non-interactive shells.

**Comment by anttikantee** [comment]
Should be fixed.  Please verify.

**Comment by jsgf** [comment]
Yep, looks good.
