### ISSUE TITLE
build-rr.sh xen fails with "xen/xen.h" not found

### ISSUE THREAD

**Issue by ilackarms** [rumpkernel/rumprun#67]
following the instructions from the build tutorial:

```
git submodule update --init
CC=cc ./build-rr.sh xen
[...]
rumprun/platform/xen/pci/../xen/include/mini-os/hypervisor.h:17:21: fatal error: xen/xen.h: No such file or directory
 #include <xen/xen.h>```

**Comment by mato** [comment]
I've added a footnote (as much as that is possible with Markdown) to the tutorial to document the need for `libxen-dev` installed when building for Xen.

**Comment by anttikantee** [comment]
I think the build system should test for and produce a more obvious error which clearly indicated that it is a configuration problem.  I'll add that soon.

**Comment by ilackarms** [comment]
great, installing `libxen-dev` solved the problem. thank you
