### ISSUE TITLE
Linker crashes during building (./build-rr.sh hw) on RHEL6v7

### ISSUE THREAD

**Issue by gnavgire** [rumpkernel/rumprun#69]
( cd rumprun/lib/librumprunfs_base &&                                                 RUMPRUN_GENFS_CC="rumprun/obj-amd64-hw/rumptools/bin/x86_64--netbsd-gcc" RUMPRUN_GENFS_OBJCOPY="rumprun/obj-amd64-hw/rumptools/bin/x86_64--netbsd-objcopy"    RUMPRUN_GENFS_INCDIR="rumprun/./obj-amd64-hw/dest.stage/include"  rumprun/./obj-amd64-hw/app-tools/x86_64-rumprun-netbsd-genfs      rumprun/./obj-amd64-hw/lib/librumprunfs_base/librumprunfs_base.a etc )
collect2: ld terminated with signal 11 [Segmentation fault]

**Comment by anttikantee** [comment]
what's the version of ld on that system? (output of `ld --verbose`)

**Comment by gnavgire** [comment]
GNU ld version 2.20.51.0.2-5.43.el6 20100205 and gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

**Comment by anttikantee** [comment]
Ok well you need something a bit more modern.  gcc 4.8 and ld 2.25 are recommended.

We'll probably eventually add a check to the build script and also a script to build a modern toolchain.  But for now, try to install one from other sources and try building with it.

**Comment by thebsdbox** [comment]
yeah, i'm surprised you even got to the linking phase as older gnu c compilers will error on a number of source files.. However, the fact that your linker segfaulted instead of producing an error is quite concerning.

**Comment by anttikantee** [comment]
It's failing in the recently-introduced genfs link (which is not a "real" link).

I don't think getting a segfault from the linker is concerning, just shows that the linker is buggy.  The fix from our perspective is very simple: don't use a buggy linker.

**Comment by gnavgire** [comment]
Its true i had to make changes for getting the source compiled on the older gcc. The src is perfectly building on newer gcc and ld versions. Thanks.
