### ISSUE TITLE
Deadlock on high-rate UDP packet sending using NetBSD virtio driver

### ISSUE THREAD

**Issue by jmmlmendes** [rumpkernel/rumprun#72]
Full test program: https://gist.github.com/jmmlmendes/aaea56a8b7044487595ef7a6782fc018

Additional details: this happens only when using KVM, not with plain QEMU.

When sending UDP packets at high rate, there is a point when ENOBUFS is always returned despite successive calls to sched_yield() to allow the actual sending to happen (and thus clearing buffers).

For example, the following piece of code will create an infinite loop:
```
void udp_flood(int fd, struct sockaddr *dst, int pktlen)
{
    struct timeval start, end;
    long long total_us = 0;
    unsigned long long pkt_sent = 0;

    gettimeofday(&start, NULL);

    while (pkt_sent < PACKETS_TO_SEND) {
        if (sendto(fd, payload, mtu, MSG_NOSIGNAL, dst, pktlen) >= 0)
            pkt_sent++;
        else
            printf("errno %d - %s\n", errno, strerror(errno));

        sched_yield();
    }

    gettimeofday(&end, NULL);
    total_us = tv_to_us(&start, &end);
    printf("%llu packets sent in %lld us\n", pkt_sent, total_us);
}
```
When sleeping between sends, this situation may not happen if the sleep time is high enough.
Seems to me that buffers are being flushed to the host except when they are full (or above a certain threshold), however, when the sending is too fast, buffers are filled and then never cleared.

Have you encountered this situation before?

**Comment by anttikantee** [comment]
Did you try if that happens with the latest NetBSD upstream (as opposed to what we have mirrored in src-netbsd)?  That's usually the best first option in cases like this.  I'm not saying the problem must be in src-netbsd, but at least based on the evidence offered, it smells a bit like that.

**Comment by jmmlmendes** [comment]
Hi Antti,

(sorry for the delay in replying)

Indeed it seems to be a problem with NetBSD (more specifically, the virtio driver)...
The same happens with both NetBSD 7.0 and the latest upstream (at least from last week).

Discussion about the issue: http://mail-index.netbsd.org/tech-net/2016/05/11/msg005855.html

Maybe this issue shouldn't be closed for now because, despite being an issue in NetBSD, it affects rump and it will remain present until the rumprun repo points to a version of NetBSD that doesn't have the issue (just my two cents, of course the decision is yours).

**Comment by anttikantee** [comment]
I agree, let's keep the issue open.

Can you verify that using the wm driver does trigger the problem in Rumprun, and change the issue title accordingly?

**Comment by jmmlmendes** [comment]
Could only reproduce the issue using virtio, not with wm - title updated.

**Comment by anttikantee** [comment]
The way `IFF_OACTIVE` is set in `vioif_start` looks suspicious.  At least per quick reading it looks like it might get set without any packet getting enqueued, and hence a transmit complete interrupt could never clear it, and hence future calls to `vioif_start` would do nothing.

You could try making sure that `IFF_OACTIVE` is set only if a packet is queued and see if that helps.

**Comment by anttikantee** [comment]
Something like this:

```
Index: if_vioif.c
===================================================================
RCS file: /cvsroot/src/sys/dev/pci/if_vioif.c,v
retrieving revision 1.22
diff -u -r1.22 if_vioif.c
--- if_vioif.c	9 Feb 2016 08:32:11 -0000	1.22
+++ if_vioif.c	12 May 2016 13:38:38 -0000
@@ -800,7 +800,6 @@
 retry:
 		r = virtio_enqueue_prep(vsc, vq, &slot);
 		if (r == EAGAIN) {
-			ifp->if_flags |= IFF_OACTIVE;
 			vioif_tx_vq_done_locked(vq);
 			if (retry++ == 0)
 				goto retry;
@@ -824,7 +823,6 @@
 			virtio_enqueue_abort(vsc, vq, slot);
 			bus_dmamap_unload(vsc->sc_dmat,
 					  sc->sc_tx_dmamaps[slot]);
-			ifp->if_flags |= IFF_OACTIVE;
 			vioif_tx_vq_done_locked(vq);
 			if (retry++ == 0)
 				goto retry;
@@ -849,11 +847,11 @@
 	}
 
 	if (m != NULL) {
-		ifp->if_flags |= IFF_OACTIVE;
 		m_freem(m);
 	}
 
 	if (queued > 0) {
+		ifp->if_flags |= IFF_OACTIVE;
 		virtio_enqueue_commit(vsc, vq, -1, true);
 		ifp->if_timer = 5;
 	}
```

nb. I didn't really think about that very carefully, but it might at least confirm the hypothesis.

**Comment by anttikantee** [comment]
Actually, that's wrong.  But at least try to confirm if `IFF_OACTIVE` is perpetually set when the buggy condition occurs.

**Comment by yasukata** [comment]
Hi Antti,

I'm working with jmmlmendes for finding out the problem.

I tried your patch, but this issue didn't disappear.

However as you say, ```IFF_OACTIVE``` seems to be continuely set if I don't modify anything.

After vioif stuck, ```sendto``` syscall seems to stop going to the driver output because the queue of ```ifnet.if_snd``` becomes full and it fails to push new packets. (In this case, virtio's ring is not full.)

I'm not sure but, this might be a possibility of deadlock.
That is ```ifnet.if_snd``` should be dequeued by driver but it doesn't reach driver because the queue is full.

By the way, we found 2 quick hacks which mitigate the issue.
When I apply those patches, I could burst UDP packet without any problem.
(Please try separetely)

First one makes it always try driver transmission even if ```IFQ_ENQUEUE``` is failed.
I think this can contribute to fix the deadlock where ```IFQ_DEQUEUE``` should be called from driver but it cannot reach driver code because the queue is full and ```IFQ_ENQUEUE``` is failed.
(This patch seems to be effective for pure NetBSD.)
```
diff --git a/sys/net/if.c b/sys/net/if.c
index 313b4c1..7de3ed0 100644
--- a/sys/net/if.c
+++ b/sys/net/if.c
@@ -2301,15 +2301,15 @@ ifq_enqueue(struct ifnet *ifp, struct mbuf *m
        IFQ_ENQUEUE(&ifp->if_snd, m, pktattr, error);
        if (error != 0)
                goto out;
        ifp->if_obytes += len;
        if (mflags & M_MCAST)
                ifp->if_omcasts++;
+out:
        if ((ifp->if_flags & IFF_OACTIVE) == 0)
                (*ifp->if_start)(ifp);
-out:
        splx(s);
        return error;
 }
```

Second one is skipping a condition for checking ```VRING_USED_F_NO_NOTIFY``` flag.
This might indicate that the issue is in the synchronization part of vioif.
(But this doesn't help in pure NetBSD.)
```
diff --git a/sys/dev/pci/virtio.c b/sys/dev/pci/virtio.c
index 60a60e6..4405dcb 100644
--- a/sys/dev/pci/virtio.c
+++ b/sys/dev/pci/virtio.c
@@ -1189,7 +1189,6 @@ notify:
                vq->vq_queued++;
                vq_sync_uring(sc, vq, BUS_DMASYNC_POSTREAD);
                membar_consumer();
-               if (!(vq->vq_used->flags & VRING_USED_F_NO_NOTIFY))
                        bus_space_write_2(sc->sc_iot, sc->sc_ioh,
                                          VIRTIO_CONFIG_QUEUE_NOTIFY,
                                          vq->vq_index);
```

I still don't understand what is the critical problem and what is the proper solution, but I hope this helps to find out.

**Comment by anttikantee** [comment]
Well, neither patch look correct.

You post seems somewhat self-contradicting, e.g. you claim that `IFF_OACTIVE` remains always set, but also that calling conditionally calling `if_start()` when `IFF_OACTIVE` is not set helps.

`IFF_OACTIVE` should get set when the driver cannot accept more packets.  It should get unset when the driver can accept more packets.  So, `IFF_OACTIVE ^ space_in_device_queue == 1`.  If that invariant does not hold, you need to figure out why.

Can you run `ifconfig <if>` when the problem appears and post the output.

**Comment by anttikantee** [comment]
Hmm, I wonder if the driver advertises a too short `ifq_maxlen`.

**Comment by anttikantee** [comment]
Well, I can't quite work out in my head how `ifq_maxlen` would cause the problem.  But I'm just trying to figure out why your first patch would fix the issue.

**Comment by anttikantee** [comment]
Maybe I'll try running your test program if I have spare time soon, should be easier to figure out what's going on if I can observe the problem myself.

**Comment by anttikantee** [comment]
Ah.  Try this patch, I'm 99% sure it will fix the problem.

```
Index: if_vioif.c
===================================================================
RCS file: /cvsroot/src/sys/dev/pci/if_vioif.c,v
retrieving revision 1.22
diff -u -r1.22 if_vioif.c
--- if_vioif.c	9 Feb 2016 08:32:11 -0000	1.22
+++ if_vioif.c	13 May 2016 17:42:36 -0000
@@ -1116,6 +1116,7 @@
 {
 	struct virtio_softc *vsc = vq->vq_owner;
 	struct vioif_softc *sc = device_private(vsc->sc_child);
+	struct ifnet *ifp = &sc->sc_ethercom.ec_if;
 	int r = 0;
 
 	VIOIF_TX_LOCK(sc);
@@ -1127,6 +1128,8 @@
 
 out:
 	VIOIF_TX_UNLOCK(sc);
+	if (r)
+		ifp->if_start(ifp);
 	return r;
 }
```

**Comment by yasukata** [comment]
Hi Antti,

I'm sorry for the delay.

I tried your patch, and it works perfectly!
It makes sense that we have to transmit packets after the virt queue becomes empty for avoiding the block at the packet queue.

I also tried your patch on NetBSD and found it drastically improves stability and performance.
Perhaps you could send this patch to NetBSD.
(Actually I still hit this issue very rarely. I expect there might be another issue...)

Thank you very much for your help!

**Comment by anttikantee** [comment]
I'll commit it to NetBSD later today.  I'll close this issue once I've committed it to NetBSD and pulled it up to src-netbsd.

Thanks for testing!

**Comment by anttikantee** [comment]
Ok the virtio patch is available in src-netbsd and rumprun.

I apparently read your mail a bit hastily in the morning.  Since I'm not exactly sure on the details of the other issue you describe, I'll leave it up to you to close this issue and open a new one or continue tracking the problem in this issue.  (If it's unclear that it's the same problem, close this and open a new one)

**Comment by jmmlmendes** [comment]
In pure NetBSD, sometimes the burst packet transmission blocks but we can't reproduce it in rump anymore: so this issue can (and should) be closed (it's nothing related to rump).
