### ISSUE TITLE
ld: -r and -pie may not be used together

### ISSUE THREAD

**Issue by pothos** [rumpkernel/rumprun#85]
_./build-rr.sh hw_ fails in linking with error `ld: -r and -pie may not be used together`
Maybe a solution is replacing `-Wl,-r` only with `-r`, but I'm not sure yet because of other compiler errors afterwards…

**Comment by mato** [comment]
What (Linux) distribution are you building on which is enabling `-pie`? The compiler specs in app-tools have never been tested in this situation and would need to be updated to disable `-pie`.

**Comment by ijackson-citrix** [comment]
Martin Lucina writes ("Re: [rumpkernel/rumprun] ld: -r and -pie may not be used together (#85)"):
> What (Linux) distribution are you building on which is enabling
> -pie? The compiler specs in app-tools have never been tested in this
> situation and would need to be updated to disable -pie.

Debian stretch's gcc generally has -pie (or something in this area)
enabled by default.

Ian.

**Comment by rtsisyk** [comment]
I have the same problem. Any news?

**Comment by harnen** [comment]
The same problem on Ubuntu 16.10

**Comment by gandro** [comment]
@harnen Regarding the error in EDIT2, this looks like issue #86 & #82 , i.e. problems with g++ 6. Currently the workarounds for this error are to either disable C++ support in Rumprun (using `CXX=false ./build-rr.sh`) or to downgrade to GCC 5.

**Comment by ijackson-citrix** [comment]
Michał Król writes ("Re: [rumpkernel/rumprun] ld: -r and -pie may not be used together (#85)"):
> @gandro Thans a lot!
> Combining CXX=false and -no-pie flags seems to work on my Ubuntu 16.10
> CXX=false ./build-rr.sh hw -- -F ACLFLAGS=-no-pie

Would someone like to prepare a pull request that fixes this in
build-rr.sh, by passing -no-pie ?  I think that flag should be fine
everywhere.

Ian.

**Comment by liuw** [comment]
Unfortunately -no-pie is not supported by all gcc versions, so it should be added conditionally.

**Comment by dysinger** [comment]
Still a problem on Ubuntu 17.04

**Comment by kent-mcleod** [comment]
On Debian Stretch when I use `CXX=false ./build-rr.sh hw -- -F ACLFLAGS=-no-pie` everything will successfully build, but when I try and compile anything with `x86_64-rumprun-netbsd-gcc` I get the error `cc1: error: command line option '--no-pie' is valid for the driver but not for C`.  Running with --verbose it seems that `-no-pie` is being passed to `/usr/lib/gcc/x86_64-linux-gnu/6/cc1` which doesn't accept that flag.  Does anyone else experience the same behavior?
