### ISSUE TITLE
Rumprun with waf

### ISSUE THREAD

**Issue by harnen** [rumpkernel/rumprun#89]
It's not really an issue, but I couldn't find any mailing list/forum to ask this question. Please let me know if there's any, so I can move my question. 

I'd like to create a unikernel from a C++ project built using [waf](https://waf.io/). Is it already possible with the current version of rumprun or does it need a special support? If it's possible do you have any hints on how to do that?

Thanks in advance,

**Comment by anttikantee** [comment]
See here: http://wiki.rumpkernel.org/Info:-Community

Maybe the rumpkernel.org front page should make it more obvious that mailing lists are behind the "community" link.
