### ISSUE TITLE
implement splfoo for real (rump is racy)

### ISSUE THREAD

**Issue by coypoop** [rumpkernel/rumprun#91]
From @akat1

    Write of size 8 at 0x7d8000044b10 by thread T31:
      #0 pool_cache_put_paddr /home/shm/src/buildrump.sh-clean/src/lib/librump/../../sys/rump/../kern/subr_pool.c:2425
             (librump.so.0+0x0000000a998d)
      #1 kmem_intr_free /home/shm/src/buildrump.sh-clean/src/lib/librump/../../sys/rump/../kern/subr_kmem.c:373
             (librump.so.0+0x0000000b2f85)
      #2 threadbouncer /home/shm/src/buildrump.sh-clean/src/lib/librump/../../sys/rump/librump/rumpkern/threads.c:85
             (librump.so.0+0x00000011a195)
    (libtsan.so.0+0x000000024b29)
    Previous read of size 8 at 0x7d8000044b10 by thread T10:
      #0 pool_cache_put_paddr /home/shm/src/buildrump.sh-clean/src/lib/librump/../../sys/rump/../kern/subr_pool.c:2408
             (librump.so.0+0x0000000a9794)
      #1 kmem_intr_free /home/shm/src/buildrump.sh-clean/src/lib/librump/../../sys/rump/../kern/subr_kmem.c:373
             (librump.so.0+0x0000000b2f85)
      #2 threadbouncer /home/shm/src/buildrump.sh-clean/src/lib/librump/../../sys/rump/librump/rumpkern/threads.c:85
             (librump.so.0+0x00000011a195)
    (libtsan.so.0+0x000000024b29)

**Comment by anttikantee** [comment]
Please provide an actual analysis instead of what, at least based on the evidence presented, looks like a jump to an incorrect conclusion ("implement splfoo").

**Comment by coypoop** [comment]
#define splvm() 0

**Comment by anttikantee** [comment]
Wrong.  Since you're not even attempting to provide an analysis *of the problem* or a how-to-repeat, I'm closing this report.
