### ISSUE TITLE
cfdriver_ioconf_virtio undeclared

### ISSUE THREAD

**Issue by sevan** [rumpkernel/rumprun#95]
Attempting to build rumprun using the latest NetBSD src (7.99.70) on OS X fails, the virtio drivers fail due to 
cfdriver_ioconf_$DRIVERNAME not being defined and cfdata_ioconf_pci_virtio being defined, but not used.

`--- virtio.o ---
#   compile  libpci_virtio/virtio.o
/Users/sme/tmp/rumprun/obj-amd64-hw-extsrc/rumptools/bin/x86_64--netbsd-gcc -O2 -g -mno-red-zone -ffreestanding -fno-strict-aliasing -mno-red-zone -mno-mmx -mno-sse -mno-avx -msoft-float   -std=gnu99    -Wall -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wno-sign-compare  -Wsystem-headers   -Wno-traditional   -Wa,--fatal-warnings  -Wreturn-type -Wswitch -Wshadow -Wcast-qual -Wwrite-strings -Wextra -Wno-unused-parameter -Wno-sign-compare -Werror -Wno-format-zero-length -Wno-pointer-sign     -I/Volumes/smh/netbsd-src-ro/src/sys/rump/dev/lib/libpci_virtio/../../../librump/rumpkern --sysroot=/Users/sme/tmp/rumprun/obj-amd64-hw-extsrc/rumptools/dest -isystem =/usr/include  -DCOMPAT_50 -DCOMPAT_60 -DCOMPAT_70 -nostdinc -imacros /Volumes/smh/netbsd-src-ro/src/sys/rump/dev/lib/libpci_virtio/../../../include/opt/opt_rumpkernel.h -imacros /Users/sme/tmp/rumprun/obj-amd64-hw-extsrc/rumptools/include/opt_buildrump.h -I/Volumes/smh/netbsd-src-ro/src/sys/rump/dev/lib/libpci_virtio -I. -I/Volumes/smh/netbsd-src-ro/src/sys/rump/dev/lib/libpci_virtio/../../../../../common/include -I/Volumes/smh/netbsd-src-ro/src/sys/rump/dev/lib/libpci_virtio/../../../include -I/Volumes/smh/netbsd-src-ro/src/sys/rump/dev/lib/libpci_virtio/../../../include/opt -I/Volumes/smh/netbsd-src-ro/src/sys/rump/dev/lib/libpci_virtio/../../../../arch -I/Volumes/smh/netbsd-src-ro/src/sys/rump/dev/lib/libpci_virtio/../../../.. -DRUMP_CURLWP=RUMP_CURLWP___THREAD -DDIAGNOSTIC -DKTRACE   -c    /Volumes/smh/netbsd-src-ro/src/sys/rump/../dev/pci/virtio.c -o virtio.o
/Volumes/smh/netbsd-src-ro/src/sys/rump/../dev/pci/virtio.c: In function 'virtio_modcmd':
/Volumes/smh/netbsd-src-ro/src/sys/rump/../dev/pci/virtio.c:1479:33: error: 'cfdriver_ioconf_virtio' undeclared (first use in this function)
   error = config_init_component(cfdriver_ioconf_virtio, 
                                 ^
/Volumes/smh/netbsd-src-ro/src/sys/rump/../dev/pci/virtio.c:1479:33: note: each undeclared identifier is reported only once for each function it appears in
/Volumes/smh/netbsd-src-ro/src/sys/rump/../dev/pci/virtio.c:1480:7: error: 'cfattach_ioconf_virtio' undeclared (first use in this function)
       cfattach_ioconf_virtio, cfdata_ioconf_virtio); 
       ^
/Volumes/smh/netbsd-src-ro/src/sys/rump/../dev/pci/virtio.c:1480:31: error: 'cfdata_ioconf_virtio' undeclared (first use in this function)
       cfattach_ioconf_virtio, cfdata_ioconf_virtio); 
                               ^
In file included from /Volumes/smh/netbsd-src-ro/src/sys/rump/../dev/pci/virtio.c:1468:0:
/Volumes/smh/netbsd-src-ro/src/sys/rump/../dev/pci/virtio.c: At top level:
./ioconf.c:49:22: error: 'cfdata_ioconf_pci_virtio' defined but not used [-Werror=unused-variable]
 static struct cfdata cfdata_ioconf_pci_virtio[] = {
                      ^
cc1: all warnings being treated as errors
`

**Comment by sevan** [comment]
Issue [resolved](https://mail-index.netbsd.org/source-changes/2017/05/10/msg084316.html)

**Comment by anttikantee** [comment]
thanks!
