### ISSUE TITLE
Consider name change Rumpkernel -> Trumpkernel

### ISSUE THREAD

**Issue by MakeItGreatAgain** [rumpkernel/rumprun#96]
It may be advantageous to change the name of Rumpkernels and Rumprun software to Trumpkernels, Trumprun, etc.  

While initially appearing humorous banality, this is just the sort of change would celebrate the historic Trump victory as well as acknowledge the culture of American Exceptionalism that led to the creation of UNIX, BSD, and efficient modern cloud computing.  

A Trumpkernel re-branding would also be virtually guaranteed to generate huge amounts of press for the project and attract developers.

NetBSD and Trump Kernels - Make Software Development Great Again!

**Comment by anttikantee** [comment]
While your suggestion has measurable merit, I prefer Kekkonels.

**Comment by nbuwe** [comment]
> I prefer Kekkonels.
Lisää sen UKK:hon! ;)
