### ISSUE TITLE
Append -no-pie when necessary

### ISSUE THREAD

**Issue by liuw** [rumpkernel/rumprun#99]
When building rumprun on Debian Stretch, it fails with something like:

```
/usr/bin/ld: -r and -pie may not be used together
```

That's due to:

1. Stretch's gcc contains -pie by default
2. Rumprun uses $(CC) to link objects

We can't simply append -no-pie because it is not supported by all gcc versions.

Adding the functionality to append -no-pie isn't too hard, but it is unclear where I should put it.

@anttikantee any suggestion?

**Comment by kent-mcleod** [comment]
Fixed by #118
